
max_post_pictures_count = 10
max_message_pictures_count = 10
allowed_img_ext = ["jpg", "jpeg", "png", "gif", "webp", "bmp", "tiff", "svg", "ico"]
max_post_pictures_size = "5MB"
max_message_pictures_size = "5MB"
max_post_text_length = 4000
max_message_text_length = 4000

max_picture_count = 10
max_picture_size = "5MB"
